// <auto-generated />
using FCApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace fcapi.Migrations
{
    [DbContext(typeof(FCDbContext))]
    [Migration("20171003170127_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FCApi.Models.Image", b =>
                {
                    b.Property<int>("imgid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("adate");

                    b.Property<string>("imgdesc");

                    b.Property<string>("imgfolder");

                    b.Property<string>("imgfullurl");

                    b.Property<string>("imgh");

                    b.Property<string>("imglink");

                    b.Property<string>("imgtitle");

                    b.Property<string>("imgurl_lg");

                    b.Property<string>("imgurl_sm");

                    b.Property<string>("imgurl_th");

                    b.Property<string>("imgw");

                    b.Property<int>("status");

                    b.HasKey("imgid");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FCApi.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("post_adate");

                    b.Property<string>("post_author");

                    b.Property<string>("post_data");

                    b.Property<string>("post_excerpt");

                    b.Property<string>("post_img");

                    b.Property<string>("post_img_title");

                    b.Property<int>("post_status");

                    b.Property<string>("post_title")
                        .IsRequired();

                    b.HasKey("PostId");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
